import Head from 'next/head'
import Image from 'next/image'
import { queryDatabase } from './api/query-database';
import styles from '../styles/Home.module.css'
import Create from './Create'

export default function Home({database}) {

  const dataArr = database.results
  const obj = {
    texts: "jjjljkl", 
    img: "lldiuqowy", 
  }

  const updateContent = () => {
    fetch('http://localhost:3000/api/create-page', { 
      method: 'post',
      body: JSON.stringify(obj), 
    })
    console.log("hahaha");
  }


  const view = {}

  dataArr.map(item => {
    const typestr = item.type
    switch (typestr) {
      case "paragraph": 
        view[typestr] = item[typestr].rich_text[0].plain_text
        break;
      case "image":
        view[typestr] = item[typestr].file.url
        break;
      case "bulleted_list_item":
        view.date = item[typestr].rich_text[0].plain_text
        break;
    }
  })

  console.info(view);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Create /> */}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <button onClick={updateContent}>dadad</button>


        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const database = await queryDatabase();

  return {
    props: {
      database,
    },
  };
}
